-- ============================================================
-- HIPSTARR PROJECT 2 — Decay Model BigQuery Updates
-- Generated by p2_01_decay_model.py
-- Run Block 1 then Block 2 separately in BigQuery
-- ============================================================

-- BLOCK 1: Update value_flow_gap with decay metrics
-- (half_life_wks, lambda, primary_market_retention, floor_pct)

UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=NULL, lambda=NULL, primary_market_retention=44.26, floor_pct=NULL WHERE track_id='NG_001';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=7.5, lambda=0.091941, primary_market_retention=47.64, floor_pct=26.91 WHERE track_id='NG_002';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=NULL, lambda=NULL, primary_market_retention=75.93, floor_pct=75.93 WHERE track_id='NG_003';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=NULL, lambda=NULL, primary_market_retention=58.82, floor_pct=57.98 WHERE track_id='NG_004';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=NULL, lambda=NULL, primary_market_retention=26.22, floor_pct=38.2 WHERE track_id='NG_005';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=NULL, lambda=NULL, primary_market_retention=48.12, floor_pct=61.18 WHERE track_id='NG_006';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=3.4, lambda=0.202942, primary_market_retention=15.6, floor_pct=13.61 WHERE track_id='NG_007';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=NULL, lambda=NULL, primary_market_retention=NULL, floor_pct=NULL WHERE track_id='ZA_001';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=14.5, lambda=0.047685, primary_market_retention=36.13, floor_pct=3.04 WHERE track_id='ZA_002';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=6.1, lambda=0.11397, primary_market_retention=12.37, floor_pct=9.54 WHERE track_id='ZA_003';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=3.6, lambda=0.19007, primary_market_retention=20.57, floor_pct=23.51 WHERE track_id='ZA_004';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=7.7, lambda=0.09019, primary_market_retention=27.16, floor_pct=17.31 WHERE track_id='ZA_005';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=NULL, lambda=NULL, primary_market_retention=NULL, floor_pct=NULL WHERE track_id='ZA_006';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=10.1, lambda=0.068602, primary_market_retention=20.15, floor_pct=2.34 WHERE track_id='ZA_007';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=0.7, lambda=1.023676, primary_market_retention=16.25, floor_pct=22.99 WHERE track_id='BR_001';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=0.9, lambda=0.753218, primary_market_retention=23.69, floor_pct=22.52 WHERE track_id='BR_002';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=22.3, lambda=0.031062, primary_market_retention=47.1, floor_pct=0.0 WHERE track_id='BR_003';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=NULL, lambda=NULL, primary_market_retention=NULL, floor_pct=NULL WHERE track_id='BR_004';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=5.3, lambda=0.130138, primary_market_retention=16.4, floor_pct=15.67 WHERE track_id='BR_005';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=22.2, lambda=0.031191, primary_market_retention=40.83, floor_pct=0.0 WHERE track_id='BR_006';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=NULL, lambda=NULL, primary_market_retention=NULL, floor_pct=NULL WHERE track_id='BR_007';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=2.2, lambda=0.312628, primary_market_retention=59.17, floor_pct=45.81 WHERE track_id='MX_001';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=7.2, lambda=0.096113, primary_market_retention=19.11, floor_pct=12.08 WHERE track_id='MX_002';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=NULL, lambda=NULL, primary_market_retention=100.0, floor_pct=NULL WHERE track_id='MX_003';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=1.6, lambda=0.433645, primary_market_retention=17.14, floor_pct=59.19 WHERE track_id='MX_004';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=15.3, lambda=0.045224, primary_market_retention=42.34, floor_pct=17.9 WHERE track_id='MX_005';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=11.9, lambda=0.058431, primary_market_retention=32.62, floor_pct=12.61 WHERE track_id='MX_006';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=11.6, lambda=0.059748, primary_market_retention=38.65, floor_pct=0.0 WHERE track_id='MX_007';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=1.6, lambda=0.422998, primary_market_retention=75.07, floor_pct=70.59 WHERE track_id='IN_001';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=NULL, lambda=NULL, primary_market_retention=NULL, floor_pct=NULL WHERE track_id='IN_002';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=6.2, lambda=0.112662, primary_market_retention=40.66, floor_pct=41.66 WHERE track_id='IN_003';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=9.1, lambda=0.076227, primary_market_retention=28.26, floor_pct=15.41 WHERE track_id='IN_004';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=9.3, lambda=0.074912, primary_market_retention=33.42, floor_pct=26.66 WHERE track_id='IN_005';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=8.7, lambda=0.079237, primary_market_retention=39.86, floor_pct=20.82 WHERE track_id='IN_006';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=7.8, lambda=0.089016, primary_market_retention=19.33, floor_pct=10.22 WHERE track_id='IN_007';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=13.9, lambda=0.050003, primary_market_retention=43.94, floor_pct=6.99 WHERE track_id='SA_001';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=24.3, lambda=0.028491, primary_market_retention=53.84, floor_pct=0.0 WHERE track_id='SA_002';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=7.0, lambda=0.098918, primary_market_retention=40.73, floor_pct=37.18 WHERE track_id='SA_003';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=6.7, lambda=0.103796, primary_market_retention=27.51, floor_pct=23.3 WHERE track_id='SA_004';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=9.3, lambda=0.074141, primary_market_retention=56.71, floor_pct=36.28 WHERE track_id='SA_005';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=1.4, lambda=0.480851, primary_market_retention=31.16, floor_pct=32.98 WHERE track_id='SA_006';
UPDATE `hipstarr_p2.value_flow_gap` SET half_life_wks=5.8, lambda=0.118951, primary_market_retention=51.87, floor_pct=45.84 WHERE track_id='SA_007';

-- BLOCK 2: Update market_streams with 6m and 12m stream totals

UPDATE `hipstarr_p2.market_streams` SET streams_6m=166307, streams_12m=166307 WHERE track_id='NG_001' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=4643592, streams_12m=6970809 WHERE track_id='NG_002' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=3968261, streams_12m=3968261 WHERE track_id='NG_003' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=7527654, streams_12m=11065786 WHERE track_id='NG_004' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=4856464, streams_12m=8299380 WHERE track_id='NG_005' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=5530757, streams_12m=9124225 WHERE track_id='NG_006' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=13805408, streams_12m=19270488 WHERE track_id='NG_007' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=NULL, streams_12m=NULL WHERE track_id='ZA_001' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=11124812, streams_12m=14625805 WHERE track_id='ZA_002' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=8864786, streams_12m=9164812 WHERE track_id='ZA_003' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=2555772, streams_12m=3676026 WHERE track_id='ZA_004' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=2573485, streams_12m=3106512 WHERE track_id='ZA_005' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=NULL, streams_12m=NULL WHERE track_id='ZA_006' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=3618576, streams_12m=3618576 WHERE track_id='ZA_007' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=45423833, streams_12m=45423833 WHERE track_id='BR_001' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=11146494, streams_12m=11146494 WHERE track_id='BR_002' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=234733265, streams_12m=334781732 WHERE track_id='BR_003' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=NULL, streams_12m=NULL WHERE track_id='BR_004' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=72097447, streams_12m=87575859 WHERE track_id='BR_005' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=213089367, streams_12m=273253145 WHERE track_id='BR_006' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=NULL, streams_12m=NULL WHERE track_id='BR_007' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=101533173, streams_12m=101533173 WHERE track_id='MX_001' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=214545393, streams_12m=284358299 WHERE track_id='MX_002' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=4933970, streams_12m=4933970 WHERE track_id='MX_003' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=4931916, streams_12m=4931916 WHERE track_id='MX_004' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=253787012, streams_12m=352729454 WHERE track_id='MX_005' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=225684489, streams_12m=315389954 WHERE track_id='MX_006' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=31864304, streams_12m=31864304 WHERE track_id='MX_007' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=87302580, streams_12m=87302580 WHERE track_id='IN_001' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=NULL, streams_12m=NULL WHERE track_id='IN_002' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=89351012, streams_12m=159038736 WHERE track_id='IN_003' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=190663926, streams_12m=269408349 WHERE track_id='IN_004' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=137207287, streams_12m=232012059 WHERE track_id='IN_005' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=168433805, streams_12m=252310543 WHERE track_id='IN_006' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=126148420, streams_12m=163268319 WHERE track_id='IN_007' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=2550019, streams_12m=2891746 WHERE track_id='SA_001' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=659826, streams_12m=659826 WHERE track_id='SA_002' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=855099, streams_12m=991578 WHERE track_id='SA_003' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=663338, streams_12m=663338 WHERE track_id='SA_004' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=1075655, streams_12m=1461920 WHERE track_id='SA_005' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=240454, streams_12m=240454 WHERE track_id='SA_006' AND is_primary_market=TRUE;
UPDATE `hipstarr_p2.market_streams` SET streams_6m=470519, streams_12m=470519 WHERE track_id='SA_007' AND is_primary_market=TRUE;
